TribaApp/Controllers/MobileController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace TribaApp.Controllers
{
    public class MobileController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult PassLeft()
        {
            return View();
        }

        public ActionResult Training()
        {
            return View();
        }

        public ActionResult MyProgress()
        {
            return View();
        }

        public ActionResult Score()
        {
            return View();
        }

        [HttpGet]
        public JsonResult VerbsTeam()
        {
            return new JsonResult { JsonRequestBehavior = JsonRequestBehavior.AllowGet, Data = new[] { new { id = 1, verb = "Put", correct = true }, new { id = 2, verb = "Cut", correct = true } } };
        }
    }
}

TribaApp/Controllers/ViewSwitcherController.cs
using System.Web.Mvc;
using System.Web.WebPages;

namespace TribaApp.Controllers
{
    public class ViewSwitcherController : Controller
    {
        public RedirectResult SwitchView(bool mobile, string returnUrl) {
            if (Request.Browser.IsMobileDevice == mobile)
                HttpContext.ClearOverriddenBrowser();
            else
                HttpContext.SetOverriddenBrowser(mobile ? BrowserOverride.Mobile : BrowserOverride.Desktop);

            return Redirect(returnUrl);
        }
    }
}

TribaApp/Views/Shared/_Layout.Mobile.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <title>@ViewBag.Title - Mobile Version</title>
    <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
    <meta name="viewport" content="width=device-width" />
    @Styles.Render("~/Content/mobilecss")
    @Styles.Render("~/Content/jquerymobilecss")
</head>
<body>
    <!-- Home -->
    <div data-role="page" id="page1">
        <div data-role="panel" id="panel1" data-position="left" data-display="reveal" data-theme="a">
            <ul data-role="listview" data-divider-theme="h" data-inset="false">
                <li data-role="list-divider" role="heading">Menu
            </li>
                <li data-theme="a">
                    <a href="@Url.Action("Index", "Mobile")" data-transition="slide">Home
                </a>
                </li>
                @if (Request.IsAuthenticated)
                {
                    <li data-theme="a">
                        <a href="@Url.Action("PassLeft", "Mobile")" data-transition="slide">Pass Left
                </a>
                    </li>
                    <li data-theme="a">
                        <a href="@Url.Action("Training", "Mobile")" data-transition="slide">Training
                </a>
                    </li>
                    <li data-theme="a">
                        <a href="@Url.Action("Score", "Mobile")" data-transition="slide">Score
                </a>
                    </li>
                    <li data-theme="a">
                        <a href="@Url.Action("MyProgress", "Mobile")" data-transition="slide">My progress
                </a></li>                                   
                }
                <li data-theme="a">
                    <a href="@Url.Action("SwitchView", "ViewSwitcher", new { mobile = false, returnUrl = "/" })" data-transition="slide">Full version</a>
                </li>
            </ul>
        </div>

        <div data-theme="a" data-role="header">
            <a data-controltype="panelbutton" data-role="button" href="#panel1" data-icon="bars"
                data-iconpos="left">Menu
            </a>
            <h3>Triba App            
            </h3>
            @Html.Partial("_LoginPartial")
            @RenderSection("featured", required: false)
        </div>
        <div data-role="content" id="welcomeView-content">
            <div data-role="navbar" data-iconpos="right">
                <ul>
                    <li>
                        <a href="#" data-transition="fade" data-theme="b" data-icon="@ViewBag.PageIcon" class="ui-btn-active ui-state-persist">@ViewBag.PageDescription
                        </a>
                    </li>
                </ul>
            </div>
            @RenderBody()
        </div>
        @Scripts.Render("~/bundles/jquery")
        <script>
            $(document).on("mobileinit", function () {
                $.mobile.ajaxEnabled = true;
            });
        </script>
        @Scripts.Render("~/bundles/jquerymobile")
        @RenderSection("scripts", required: false)
    </div>
</body>
</html>

TribaApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <title>@ViewBag.Title - My ASP.NET MVC Application</title>
    <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- Loading Bootstrap -->
    <link href="/Content/bootstrap/css/bootstrap.css" rel="stylesheet">

    <!-- Loading Flat UI -->
    <link href="/Content/flat/flat-ui.css" rel="stylesheet">

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements. All other JS at the end of file. -->
    <!--[if lt IE 9]>
      <script src="js/html5shiv.js"></script>
    <![endif]-->
</head>
<body>
    <header>
        <div class="content-wrapper">
            <div class="float-left">
                <p class="site-title">@Html.ActionLink("your logo here", "Index", "Home")</p>
            </div>
            <div class="float-right">
                <section id="login">
                    @Html.Partial("_LoginPartial")
                </section>
                <nav>
                    <ul id="menu">
                        <li>@Html.ActionLink("Home", "Index", "Home")</li>
                        <li>@Html.ActionLink("About", "About", "Home")</li>
                        <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                        @if (Request.Browser.IsMobileDevice)
                        {
                            <li><a href="@Url.Action("SwitchView", "ViewSwitcher", new { mobile = true, returnUrl = "/" })" data-transition="slide">Mobile</a></li>
                        }
                    </ul>
                </nav>
            </div>
        </div>
    </header>
    @RenderSection("featured", required: false)
    
    
    <div class="row demo-row">
        <div class="span9">
          <div class="navbar navbar-inverse">
            <div class="navbar-inner">
              <div class="container">
                <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target="#nav-collapse-01"></button>
                <div class="nav-collapse collapse" id="nav-collapse-01">
                  <ul class="nav">
                    <li>
                      <a href="#fakelink">
                        Menu Item
                        <span class="navbar-unread">1</span>
                      </a>
                    </li>
                    <li class="active">
                      <a href="#fakelink">
                        Messages
                        <span class="navbar-unread">1</span>
                      </a>
                      <ul>
                        <li><a href="#fakelink">Element One</a></li>
                        <li>
                          <a href="#fakelink">Sub menu</a>
                          <ul>
                            <li><a href="#fakelink">Element One</a></li>
                            <li><a href="#fakelink">Element Two</a></li>
                            <li><a href="#fakelink">Element Three</a></li>
                          </ul> <!-- /Sub menu -->
                        </li>
                        <li><a href="#fakelink">Element Three</a></li>
                      </ul> <!-- /Sub menu -->
                    </li>
                    <li>
                      <a href="#fakelink">
                        About Us
                      </a>
                    </li>
                  </ul>
                </div><!--/.nav -->
              </div>
            </div>
          </div>
        </div>        
      </div>
    
    		
    <div class="container">
        @RenderBody()
    </div>
    <!-- /.container -->
    <!-- Load JS here for greater good =============================-->
    @Scripts.Render("~/bundles/jquery")

    <script src="/Scripts/flat/jquery-ui-1.10.3.custom.min.js"></script>
    <script src="/Scripts/flat/jquery.ui.touch-punch.min.js"></script>
    <script src="/Scripts/flat/bootstrap.min.js"></script>
    <script src="/Scripts/flat/bootstrap-select.js"></script>
    <script src="/Scripts/flat/bootstrap-switch.js"></script>
    <script src="/Scripts/flat/flatui-checkbox.js"></script>
    <script src="/Scripts/flat/flatui-radio.js"></script>
    <script src="/Scripts/flat/jquery.tagsinput.js"></script>
    <script src="/Scripts/flat/jquery.placeholder.js"></script>
    @RenderSection("scripts", required: false)
</body>
</html>

TribaApp/Views/Shared/_LoginPartial.Mobile.cshtml
@if(Request.IsAuthenticated) {
    @Html.ActionLink(User.Identity.Name, "Index", "Account", routeValues: null, htmlAttributes: new { data_icon = "gear" })
}
else {
    @Html.ActionLink("Log in", "Login", "Account", routeValues: null, htmlAttributes: new { data_icon = "gear" })
}

TribaApp/Views/Shared/_ViewSwitcher.cshtml
@if (Request.Browser.IsMobileDevice && Request.HttpMethod == "GET")
{
    <div class="view-switcher ui-bar-a">
        @if (ViewContext.HttpContext.GetOverriddenBrowser().IsMobileDevice)
        {
            @: Displaying mobile view
            @Html.ActionLink("Desktop view", "SwitchView", "ViewSwitcher", new { mobile = false, returnUrl = Request.Url.PathAndQuery }, new { rel = "external" })
        } 
        else 
        {
            @: Displaying desktop view
            @Html.ActionLink("Mobile view", "SwitchView", "ViewSwitcher", new { mobile = true, returnUrl = Request.Url.PathAndQuery }, new { rel = "external" })
        }
    </div>
}